CREATE TABLE J_MEMBER (
    MEMBER_NO NUMBER 
    ,ID VARCHAR2(100)
    ,PWD VARCHAR2(100)
    ,NICK VARCHAR2(100)
    ,QUIT_YN CHAR(1)
);
-- JOIN¹®
INSERT INTO J_MEMBER (MEMBER_NO,ID,PWD,NICK,QUIT_YN) VALUES(
NVL((SELECT J.MEMBER_NO FROM J_MEMBER J WHERE ROWNUM = 1), 0) + 1,'USER01','1234','USER01','N'
);
-- LOGIN¹®
SELECT * FROM J_MEMBER WHERE ID = 'USER01' AND PWD = '1234' ;

CREATE TABLE J_BOARD(
    TITLE VARCHAR2(100)
    ,CONTENT VARCHAR2(4000)
    ,WRITER_NO NUMBER
    ,ENROLL_DATE TIMESTAMP
    ,DEL_YN CHAR(1)
);