-- 계정 만들기
CREATE USER C##KH IDENTIFIED BY 1234;

-- 접속권한 , 리소스권한 부여
GRANT CONNECT, RESOURCE TO C##KH;

-- 테이블스페이스 권한 부여
ALTER USER C##KH DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

-- 시스템 계정에서만 가능 (최상위 권한을 가지고 있기 때문에)


/*
CREATE TABLE MEMBER(
    ID VARCHAR2(100),
    PWD VARCHAR2(100),
);

-- 테이블 조회
SELECT * FROM MEMBER;
SELECT * FROM MEMBER WHERE ID ='abc';
SELECT * FROM MEMBER WHERE PWD ='0000';

--값 INSERT 추가
INSERT INTO MEMBER(ID,PWD) VALUES ('USER01','1234');
INSERT INTO MEMBER(ID,PWD) VALUES ('USER02','1234');
INSERT INTO MEMBER(ID,PWD) VALUES ('USER03','1234');
INSERT INTO MEMBER(ID,PWD) VALUES ('USER04','1234');
INSERT INTO MEMBER(ID,PWD) VALUES ('USER05','1234');

INSERT INTO MEMBER(ID,PWD) VALUES ('abc','0000');

--테이블 삭제 DELETE는 행 삭제 / DROP은 테이블 삭제 (DROP은 롤백이 안됨)
DELETE FROM MEMBER WHERE ID ='abc';
DELETE FROM MEMBER;
DROP TABLE MEMBER;
*/








